name: Demo Site
favicon: null
layout_spectrum: 0.13659
typography_spectrum: 0.7970634084194899
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#6d6e72'
    - '#0f0f0f'
    - '#46a7c7'
    - '#d1d1d1'
  brandStrength: 0.34939711866900325
  lightness: 0.375
  saturation: 0
  rhythmicContrast: 1
purpose: []
